version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zerxy
      POSTGRES_DB: coba
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_DSN: "host=db user=postgres password=zerxy dbname=coba port=5432 sslmode=disable TimeZone=Asia/Jakarta"
    command: ["go", "run", "main.go"]

volumes:
  pgdata:
